# Generated by Django 4.0.4 on 2022-05-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='review_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pick',
            name='building_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.building'),
        ),
        migrations.AddField(
            model_name='pick',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='building_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.building'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('user_email', 'building_id')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user_email', 'building_id')},
        ),
        migrations.RemoveField(
            model_name='pick',
            name='building',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='building',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
